package authentication_project.fido.common.exception

class NotFoundUserException(message: String) : RuntimeException(message) {
}